---
- hosts: local
  remote_user: vagrant
  become: true

  pre_tasks:
    - name: Autofollow to project on logon
      lineinfile:
        dest: /home/vagrant/.bashrc
        regexp: ^cd /vagrant
        line: cd /vagrant

    - name: Set env variable
      lineinfile:
        dest: /home/vagrant/.bashrc
        regexp: ^export {{ item.var }}=
        line: export {{ item.var }}={{ item.value }}
      with_items:
      - { var: RAILS_ENV, value: development }

    - name: Install a list of APT packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - build-essential
          - libpq-dev
          - libsqlite3-dev

  roles:
    - role: rbenv
    - role: nodejs
    - role: ntp
    - role: postgresql

  post_tasks:
    - name: Install Ruby gems
      become: false
      bundler:
        executable: ~/.rbenv/shims/bundle
        gemfile: /vagrant/Gemfile
        state: present

    # - name: Run migration for databases
    #   become: false
    #   command: ~/.rbenv/shims/rails db:migrate chdir=/vagrant

    # - name: Run migration for databases
    #   become: false
    #   command: RAILS_ENV=test ~/.rbenv/shims/rails db:migrate chdir=/vagrant
